name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - id: get-version
        uses: battila7/get-version-action@v2

      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - id: release-asset
        run: |
          version=${{ steps.get-version.outputs.version-without-v }}
          cd ..
          cp -r fmscan fmscan-$version
          rm -rf fmscan-$version/.git*
          tar zcfv fmscan-$version.tar.gz fmscan-$version

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: ../fmscan-*.tar.gz
